<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AlgoName>ReversalScanner</AlgoName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="*-*" />
  </ItemGroup>

  <Target Name="_OverrideAlgoFileName" BeforeTargets="_ExtractMetadata">
    <PropertyGroup>
      <_AlgoFileName>ReversalScanner.algo</_AlgoFileName>
      <_AlgoFilePath>$(OutDir)$(_AlgoFileName)</_AlgoFilePath>
      <_AlgoMetadataFileName>$(_AlgoFileName).metadata</_AlgoMetadataFileName>
      <_AlgoMetadataFilePath>$(OutDir)$(_AlgoMetadataFileName)</_AlgoMetadataFilePath>
    </PropertyGroup>
  </Target>

</Project>
